windowrule {
  name = windowrule-1
  workspace = 9
  match:class = ^(brave-discord.com__channels_@me-Default)$
}

windowrule {
  name = windowrule-2
  workspace = 6
  match:class = ^(brave-grok.com__-Defauolt)$
}

windowrule {
  name = windowrule-3
  workspace = 6
  match:class = ^(brave-claude.ai__new-Default)$
}

windowrule {
  name = windowrule-4
  workspace = 8
  match:class = ^(steam)$
}

windowrule = float off, match:class steam

windowrule {
  name = windowrule-5
  workspace = 4
  match:class = ^(steam_app_1062090)$ # Timberborn
}

windowrule {
  name = windowrule-6
  workspace = 4
  match:class = ^(steam_app_3361510)$ # Coal LLC
}

windowrule {
  name = windowrule-7
  workspace = 4
  match:class = ^(steam_app_1284190)$ # Planet Crafter
}
